[pytest]
asyncio_mode = auto
filterwarnings =
    ignore:The `parse_obj` method is deprecated.*:pydantic.warnings.PydanticDeprecatedSince20:langchain_core.tools.base
    ignore:The `dict` method is deprecated.*:pydantic.warnings.PydanticDeprecatedSince20:langchain_core.tools.base
testpaths = tests
pythonpath = ..
