/* Browser business regressions. All write endpoints are intercepted. */
const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.NEXUS_TEST_BROWSER?{executablePath:process.env.NEXUS_TEST_BROWSER}:{})});
 const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.NEXUS_TEST_URL||'http://127.0.0.1:30000/',{waitUntil:'networkidle'});
 const check=async(condition,label)=>{if(!await condition)throw Error(label);console.log('PASS '+label);};
 await check(page.evaluate(()=>{const b=document.createElement('button');document.body.append(b);setBusy(true);setBusy(true);setBusy(false);const ok=!b.disabled;b.remove();return ok;}),'repeated busy entry does not permanently disable buttons');
 let savedBody=null;
 const action={type:'confirmation',action_id:'audit-schedule',title:'定时转账测试',detail:'收款人：测试\n金额：1000元',editable:['amount','purpose','run_date'],terms:{amount:'1000.00',purpose:'测试',frequency:'weekly',first_run_on:'2026-12-01',occurrences:2},expires_at:new Date(Date.now()+300000).toISOString()};
 await page.route('**/api/actions/audit-schedule',async route=>{savedBody=route.request().postDataJSON();await route.fulfill({json:action});});
 await page.evaluate(a=>renderAnswer(a),action);
 let card=page.locator('[data-action-id="audit-schedule"]');
 await card.getByRole('button',{name:'修改这笔',exact:true}).click();
 await check(card.locator('[data-edit-field="amount"]').inputValue().then(v=>v==='1000.00'),'editable money contains no thousands separator');
 await card.getByRole('button',{name:'保存修改',exact:true}).click();await page.waitForFunction(()=>!busy);
 await check(Promise.resolve(savedBody?.recurrence==='weekly'&&savedBody?.occurrences===2&&savedBody?.amount==='1000.00'),'scheduled edit submits date cadence count and amount');
 await check(card.getByRole('button',{name:'确认执行',exact:true}).isEnabled(),'scheduled edit restores confirmation');
 await check(page.evaluate(()=>scheduleLabel({frequency:'ONCE'})==='仅此一次'&&scheduleLabel({frequency:'WEEKLY'})==='每周'&&scheduleLabel({frequency:'MONTHLY',day_of_month:8})==='每月8日'),'schedule summary respects recurrence');
 const expiring={...action,action_id:'audit-expiring',expires_at:new Date(Date.now()+1000).toISOString()};
 await page.evaluate(a=>{renderAnswer(a);setBusy(true);},expiring);await page.waitForTimeout(1400);await page.evaluate(()=>setBusy(false));
 await check(page.locator('[data-action-id="audit-expiring"]').getByRole('button',{name:'确认执行',exact:true}).isDisabled(),'expiry during pending request stays disabled after busy ends');
 let setupCalls=0,verifyCalls=0;
 await page.route('**/api/step-up/passcode',async route=>{setupCalls++;await new Promise(r=>setTimeout(r,100));await route.fulfill({json:{ok:true}});});
 await page.route('**/api/actions/audit-step/step-up',async route=>{verifyCalls++;await new Promise(r=>setTimeout(r,120));await route.fulfill({status:400,json:{message:'测试核验失败'}});});
 const step={type:'step_up',action_id:'audit-step',title:'二次核验测试',detail:'核对金额',editable:['amount'],terms:{amount:'100'},challenge:{fields:[{name:'amount',label:'金额',format:'money'}],passcode_required:true,passcode_length:4},expires_at:new Date(Date.now()+300000).toISOString()};
 await page.evaluate(a=>{demoPasscode='1234';renderAnswer(a);},step);
 const stepCard=page.locator('.step-up-card').last();
 await stepCard.locator('[data-setup-passcode]').fill('2468');
 await stepCard.locator('.step-up-setup-form').evaluate(form=>form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
 await page.waitForFunction(()=>!busy);
 await check(Promise.resolve(setupCalls===1&&verifyCalls===0),'setting passcode never submits transaction verification');
 await check(stepCard.locator('.step-up-demo-code').count().then(n=>n===0),'old demo passcode hidden after changing password');
 await stepCard.locator('[data-step-field="amount"]').fill('100');await stepCard.locator('[data-step-field="passcode"]').fill('2468');
 await stepCard.locator('.step-up-form').evaluate(form=>{for(let i=0;i<2;i++)form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));});await page.waitForFunction(()=>!busy);
 await check(Promise.resolve(verifyCalls===1),'double Enter sends only one verification request');
 await stepCard.getByRole('button',{name:'改金额后重试',exact:true}).click();
 await check(stepCard.locator('.step-up-form').evaluate(form=>form.inert),'verification cannot submit while changed terms are being edited');
 await stepCard.getByRole('button',{name:'不改了',exact:true}).click();
 await check(stepCard.locator('.step-up-form').evaluate(form=>!form.inert),'cancel editing restores verification form');
 await page.route('**/api/overview',async route=>route.fulfill({status:500,json:{message:'测试刷新失败'}}));
 await page.route('**/api/actions/audit-schedule/confirm',async route=>route.fulfill({json:{type:'receipt',action_id:action.action_id,title:'测试已执行',detail:'金额：1000元',reference:'TEST-ONLY'}}));
 const failuresBefore=await page.locator('.failure-card').count();await card.getByRole('button',{name:'确认执行',exact:true}).click();await page.waitForFunction(()=>!busy);
 await check(page.getByText('测试已执行',{exact:true}).isVisible(),'acknowledged receipt retained when sidebar refresh fails');
 await check(page.locator('.failure-card').count().then(n=>n===failuresBefore),'refresh failure never becomes retryable execution failure');
 await check(page.locator('#error').innerText().then(t=>t.includes('无需重复提交')),'refresh warning does not claim transfer failed');
 let riskCalls=0;
 await page.route('**/api/risk-assessment',async route=>{riskCalls++;await new Promise(r=>setTimeout(r,100));await route.fulfill({json:{type:'message',message:'测试测评已保存'}});});
 await page.evaluate(()=>renderAnswer({type:'risk_intake',title:'测评测试',questions:[{name:'experience',prompt:'测试选择',hint:'',options:[{label:'有经验',hint:''}]}]}));
 const riskForm=page.locator('.risk-form').last();await riskForm.locator('label.risk-option').click();
 await riskForm.evaluate(form=>{for(let i=0;i<2;i++)form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));});await page.waitForFunction(()=>!busy);
 await check(Promise.resolve(riskCalls===1),'risk questionnaire double Enter submits only once');
 let messages=[];
 await page.route('**/api/messages',async route=>{messages.push(route.request().postDataJSON());await route.fulfill(messages.length===1?{status:500,json:{message:'测试计划请求失败'}}:{json:{type:'message',message:'测试生日计划已生成'}});});
 await page.evaluate(()=>renderAnswer({type:'birthday_intake',title:'生日测试',message:'填写日期和预算',min_date:'2026-01-01',budget:'500'}));
 const birthday=page.locator('.birthday-form').last();await birthday.locator('input[type="date"]').fill('2026-12-01');
 await birthday.getByRole('button',{name:'继续生成跨场景计划'}).click();await page.waitForFunction(()=>!busy);
 await check(birthday.isVisible(),'birthday form and inputs survive failed planning request');
 await birthday.getByRole('button',{name:'继续生成跨场景计划'}).click();await page.waitForFunction(()=>!busy);
 await check(Promise.resolve(messages.length===2&&messages[0].request_id===messages[1].request_id),'birthday retry reuses request id instead of duplicating task');
 await check(page.locator('.birthday-form').count().then(n=>n===0),'birthday form closes only after successful result');
 await page.evaluate(a=>{renderAnswer({...a,action_id:'audit-old-timer'});const old=seenActions.get('audit-old-timer');const stop=old.stopCountdown;window.stoppedOldCountdown=false;old.stopCountdown=()=>{window.stoppedOldCountdown=true;stop();};renderAnswer({...a,action_id:'audit-old-timer',detail:'更新后的条款'});},action);
 await check(page.evaluate(()=>window.stoppedOldCountdown),'replacing confirmation stops old expiry timer');
 await check(Promise.resolve(errors.length===0),'no JavaScript errors across business flows');
 await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
